"""empty message

Revision ID: 7155bb9b7ac2
Revises: a76b699c50f7
Create Date: 2025-02-25 17:27:04.207123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7155bb9b7ac2'
down_revision = 'a76b699c50f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=250), nullable=False),
    sa.Column('password', sa.VARCHAR(length=60), nullable=False),
    sa.PrimaryKeyConstraint('ID'),
    sa.UniqueConstraint('ID'),
    sa.UniqueConstraint('email')
    )
    op.create_table('dashboard',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('User_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.String(length=250), nullable=False),
    sa.Column('time', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['User_id'], ['users.ID'], ),
    sa.PrimaryKeyConstraint('ID'),
    sa.UniqueConstraint('ID')
    )
    op.drop_table('Films')
    op.drop_table('Users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Users',
    sa.Column('ID', sa.INTEGER(), nullable=False),
    sa.Column('email', sa.VARCHAR(length=250), nullable=False),
    sa.Column('password', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('ID'),
    sa.UniqueConstraint('ID'),
    sa.UniqueConstraint('email')
    )
    op.create_table('Films',
    sa.Column('ID', sa.INTEGER(), nullable=False),
    sa.Column('User_id', sa.INTEGER(), nullable=False),
    sa.Column('level', sa.VARCHAR(length=250), nullable=False),
    sa.Column('time', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['User_id'], ['Users.ID'], ),
    sa.PrimaryKeyConstraint('ID'),
    sa.UniqueConstraint('ID')
    )
    op.drop_table('dashboard')
    op.drop_table('users')
    # ### end Alembic commands ###
