"""empty message

Revision ID: a76b699c50f7
Revises: 3fe759ee6844
Create Date: 2025-02-25 16:43:57.754605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a76b699c50f7'
down_revision = '3fe759ee6844'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.drop_column('username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.VARCHAR(length=250), nullable=True))

    # ### end Alembic commands ###
